### ISSUE TITLE
What is the LDAmapping?

### ISSUE THREAD

**Issue by Enghsaal170** [JaeyoungShin/simultaneous_EEG-NIRS#2]
Dear Experts 

Unrecognized function or variable 'LDAmapping'.

Error in Dataset_C_meta_classification (line 192)
                map_train.deoxy.x = LDAmapping(C.deoxy, fv_train.deoxy.x, 'meta');

Any help or suggestion  is much appreciated

**Comment by xaiohuohuo** [comment]
Dear Experts

Unrecognized function or variable 'LDAmapping'.

Error in Dataset_C_meta_classification (line 192)
map_train.deoxy.x = LDAmapping(C.deoxy, fv_train.deoxy.x, 'meta');

Any help or suggestion is much appreciated
